[project]
name = "indappproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "piper-tts>=1.2.0",
    "uvicorn>=0.35.0",
]
