services:
  ollama_prod:
    build:
      context: ollama
      dockerfile: Dockerfile
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    expose:
      - "11434:11434"
    profiles:
      - prod
  ollama_dev:
    build:
      context: ollama
      dockerfile: Dockerfile
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    ports:
      - "11434:11434"
    profiles:
      - dev
      - backend
  piper_prod:
    build:
      context: piper
      dockerfile: Dockerfile
    environment:
      - PIPER_VOICE=en_US-hfc_female-medium
      - PORT=5000
    container_name: piper
    expose:
      - "5000:5000"
    profiles:
      - prod
  piper_dev:
    build:
      context: piper
      dockerfile: Dockerfile
    environment:
      - PIPER_VOICE=en_US-hfc_female-medium
      - PORT=5000
    container_name: piper
    ports:
      - "5000:5000"
    profiles:
      - dev
      - backend
  premium_prod:
    build:
      context: premium
      dockerfile: Dockerfile
    container_name: premium
    expose:
      - "5432:5432"
    profiles:
      - prod
    volumes:
      - ./premium/premium_data:/var/lib/postgresql/data
  premium_dev:
    build:
      context: premium
      dockerfile: Dockerfile
    container_name: premium
    ports:
      - "5432:5432"
    profiles:
      - dev
      - backend
    volumes:
      - ./premium/premium_data:/var/lib/postgresql/data
  travelmate_prod:
    build:
      context: ../
      dockerfile: docker/travelmate/Dockerfile.prod
    container_name: travelmate
    environment:
      - APP_MODE=prod
      - LLM_URL=http://ollama:11434
      - PIPER_URL=http://piper:5000
      - PREMIUM_URL=http://premium:5432
    ports:
      - "3000:3000"
    depends_on:
      - ollama_prod
      - piper_prod
      - premium_prod
    profiles:
      - prod
  travelmate_dev:
    build:
      context: ../
      dockerfile: docker/travelmate/Dockerfile.dev
    container_name: travelmate
    environment:
      - APP_MODE=dev
      - LLM_URL=http://ollama:11434
      - PIPER_URL=http://piper:5000
      - PREMIUM_URL=http://premium:5432
    ports:
      - "3000:3000"
    depends_on:
      - ollama_dev
      - piper_dev
      - premium_dev
    volumes:
      - ../:/app
    profiles:
      - dev
    